# This configuration file tells Netlify how to build and deploy your main site.
# Place this in the root of your "Site Mills" project folder.

[build]
  # This tells Netlify that all files in the root should be published.
  # This ensures your "pages" folder and everything in it gets deployed.
  publish = "."

# You can also add form settings here for clarity, though they are often automatic.
[functions]
  # No functions needed for this project.

# Form handling settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

